- name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add date_meciuri.json
          # Verificăm dacă există modificări înainte de commit
          if git diff --quiet && git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update meciuri"
            git push
          fi
